#!/bin/sh
if [ "$METHOD" = loopback ]; then
    exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
    exit 0
fi

cp /etc/issue-standard /etc/issue
/opt/vm-scripts/scripts/get-ip-address >> /etc/issue
/opt/vm-scripts/scripts/get-archie-ver >> /etc/issue
echo "" >> /etc/issue
